name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  lint:
    name: Lint 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: cargo clippy
        run: ./lint.sh
  build:
    name: Build 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Build examples
        run: cargo build --examples
      - name: Run tests
        run: cargo test --all-targets
  publish:
    runs-on: ubuntu-20.04
    needs: [lint, build]
    if: startswith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Install requirements
        run: pip install toml
      - name: Set version in Cargo.toml
        run: ./scripts/set_version.py Cargo.toml ${{ steps.get_version.outputs.VERSION }}
      - name: Publish
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }} --allow-dirty
